### ISSUE TITLE
hide element in Internet Explorer

### ISSUE THREAD

**Issue by Mexikaner9** [stowball/Layout-Engine#12]
Hello
I have a rotating cube, but this does not work in Internet Explorer.
Can you please tell me what CSS code I need to hide the cube in Internet Explorer?
And this is my example: http://dauten.server29.vorschauseite.eu/CUBE/ 
thank you in advance!

**Comment by stowball** [comment]
Not that I agree with hiding content, but if you must, then `.vendor-ie .cubeee { display: none; }` should do the trick

**Comment by Mexikaner9** [comment]
Many thanks for your response!
If you think that this is not the perfect solution, what is your recommendation?
Have a nice day
