### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by evoleinik** [stowball/Layout-Engine#6]
Hello!

It would be nice to have Bower support!

Thank you!

**Comment by noisysocks** [comment]
+1

**Comment by connorbond** [comment]
+1

**Comment by gumelar** [comment]
+1

**Comment by 3R-soft** [comment]
+1

**Comment by stowball** [comment]
Just pushed a bug fix to detect IE11 on Win 10 and added layout-engine to bower
